adminMedia_index:
    path:     /
    defaults: { _controller: "EcommerceBundle:MediaAdmin:index" }
    methods:  GET

adminMedia_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:MediaAdmin:show" }
    methods:  GET

adminMedia_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:MediaAdmin:new" }
    methods:  [GET, POST]

adminMedia_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:MediaAdmin:edit" }
    methods:  [GET, POST]

adminMedia_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:MediaAdmin:delete" }
    methods:  DELETE
