products_index:
    path:     /
    defaults: { _controller: "EcommerceBundle:ProductsAdmin:index" }
    methods:  GET

products_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:ProductsAdmin:show" }
    methods:  GET

products_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:ProductsAdmin:new" }
    methods:  [GET, POST]

products_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:ProductsAdmin:edit" }
    methods:  [GET, POST]

products_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:ProductsAdmin:delete" }
    methods:  DELETE
