adminProducts_index:
    path:     /
    defaults: { _controller: "EcommerceBundle:ProductsAdmin:index" }
    methods:  GET

adminProducts_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:ProductsAdmin:show" }
    methods:  GET

adminProducts_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:ProductsAdmin:new" }
    methods:  [GET, POST]

adminProducts_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:ProductsAdmin:edit" }
    methods:  [GET, POST]

adminProducts_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:ProductsAdmin:delete" }
    methods:  DELETE
