cart:
    path:     /
    defaults: { _controller: "EcommerceBundle:Cart:cart" }
    methods:  [GET, POST]
shipping:
    path:     /shipping
    defaults: { _controller: "EcommerceBundle:Cart:shipping" }
    methods: [GET, POST]
add:
    path:     /add/{id}
    defaults: { _controller: "EcommerceBundle:Cart:add" }
    methods:  [GET, POST]
remove:
    path:     /remove/{id}
    defaults: { _controller: "EcommerceBundle:Cart:remove" }
    methods:  [GET, POST]
    
removeShippingAddress:
    path:     /shipping/remove/address/{id}
    defaults: { _controller: "EcommerceBundle:Cart:removeAddress" }
    methods:  [GET, POST]

validation:
    path:     /validation
    defaults: { _controller: "EcommerceBundle:Cart:validation" }
    methods:  [GET, POST]
    
validationOrder:
    path:     /order/validation/{id}
    defaults: { _controller: "EcommerceBundle:Orders:validationOrder" }
