send_email:
    path:     /send-email/{name}
    defaults: { _controller: "EcommerceBundle:Default:sendEmail" }
    methods:  [GET, POST]

ecommerce_about:
    path:     /
    defaults: { _controller: "EcommerceBundle:Default:index" }
    methods:  [GET, POST]
    
ecommerce_contact:
    path:     /contact
    defaults: { _controller: "EcommerceBundle:Default:contact" }
    methods:  [GET, POST]