<?php

namespace EcommerceBundle\Repository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($string)
    {
        $qb =  $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.name like :string')
                    ->andWhere('u.available = 1')
                    ->orderBy('u.id')
                    ->setParameter('string', '%'.$string.'%');
        return $qb->getQuery()->getResult();
    }
    
    public function findArray($keys)
    {
        $qb =  $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.id IN (:array)')
                    ->setParameter('array', $keys);
        return $qb->getQuery()->getResult();
    }
}
