<?php

namespace EcommerceBundle\Repository;

/**
 * UsersAddressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersAddressesRepository extends \Doctrine\ORM\EntityRepository
{
}
