users_users:
    resource: "@UsersBundle/Controller/UsersController.php"
    type:     annotation

users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en
        