users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en
        