# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
#    taxe:
#        class: EcommerceBundle\Twig\Extension\TaxeExtension
#        public: false
#        tags:
#            - { name: txig.extension }
