routingDefault:
    resource: "@EcommerceBundle/Resources/config/routing/default.yml"
    prefix: /
    
routingProductsAdmin:
    resource: "@EcommerceBundle/Resources/config/routingAdmin/products.yml"
    prefix: /admin/products
    
routingMediaAdmin:
    resource: "@EcommerceBundle/Resources/config/routingAdmin/media.yml"
    prefix: /admin/media

routingCategoriesAdmin:
    resource: "@EcommerceBundle/Resources/config/routingAdmin/categories.yml"
    prefix: /admin/categories
    
routingProducts:
    resource: "@EcommerceBundle/Resources/config/routing/products.yml"
    prefix: /products
    
routingCart:
    resource: "@EcommerceBundle/Resources/config/routing/cart.yml"
    prefix: /cart
    

